# 2025-07-20 CH41B01
# Fixed Production N8N Deployment with Logging

services:
  # Caddy Reverse Proxy
  caddy:
    image: caddy:2-alpine
    container_name: n8n-caddy-fixed
    restart: unless-stopped
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - ./security/Caddyfile-simple:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - ./logs/caddy:/var/log/caddy:rw
    networks:
      - n8n-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # N8N Application
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-app-fixed
    restart: unless-stopped
    expose:
      - "5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENCRYPTION_KEY=N8nPr0duct10nK3yVeryL0ngAndS3cur3Ch4ng3Th1sInPr0duct10n2025
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin_6290
      - N8N_BASIC_AUTH_PASSWORD=SecureRandomP@ssw0rd2025!
      - N8N_DISABLE_UI=false
      - N8N_SECURE_COOKIE=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - WEBHOOK_URL=https://localhost
      - NODE_ENV=production
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_prod_7361
      - DB_POSTGRESDB_USER=n8n_user_5128
      - DB_POSTGRESDB_PASSWORD=Sup3rS3cur3DBP@ssw0rd2025!
      - DB_POSTGRESDB_CONNECTION_TIMEOUT=60000
      - DB_POSTGRESDB_POOL_SIZE=5
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - TZ=UTC
    volumes:
      - n8n-data:/home/node/.n8n
      - ./logs/n8n:/var/log/n8n:rw
    networks:
      - n8n-network
    depends_on:
      postgres:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "node"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: n8n-postgres-fixed
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n_prod_7361
      - POSTGRES_USER=n8n_user_5128
      - POSTGRES_PASSWORD=Sup3rS3cur3DBP@ssw0rd2025!
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql:rw
    networks:
      - n8n-network
    expose:
      - "5432"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n_user_5128 -d n8n_prod_7361"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 45s

  # Grafana Monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: n8n-grafana-fixed
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Gr@fanaS3cur3P@ss2025!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=https://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=strict
      - GF_LOG_LEVEL=info
    volumes:
      - grafana-data:/var/lib/grafana
      - ./logs/grafana:/var/log/grafana:rw
    networks:
      - n8n-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "472:472"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  caddy-data:
  caddy-config:
  n8n-data:
  postgres-data:
  grafana-data:

networks:
  n8n-network:
    driver: bridge
