version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-test
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_DISABLE_UI=false
      - NODE_ENV=development
      - N8N_LOG_OUTPUT=console
      - N8N_LOG_LEVEL=info
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_FOLDER=W:\DEV\0xdx-n8n\data
      - N8N_ENCRYPTION_KEY=TESTKEY123456789012345678901234
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - W:\DEV\0xdx-n8n\data:/home/node/.n8n
      - W:\DEV\0xdx-n8n\logs:/var/log/n8n
    networks:
      - n8n-test-net

networks:
  n8n-test-net:
    driver: bridge
