# 2025-07-20 CH41B01
# Prometheus configuration for secure N8N monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    deployment: 'n8n-secure'
    maintainer: '0xdx'

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http
    
  # N8N application monitoring
  - job_name: 'n8n-app'
    static_configs:
      - targets: ['n8n:5678']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http
    scrape_timeout: 10s
    honor_labels: true
    
  # Caddy reverse proxy monitoring
  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2019']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http
    
  # PostgreSQL database monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['n8n-db:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http
    params:
      'collect[]':
        - pg_stat_database
        - pg_stat_bgwriter
        - pg_stat_user_tables
        - pg_locks
        - pg_settings
        
  # Container health monitoring
  - job_name: 'container-health'
    static_configs:
      - targets: ['caddy:80', 'n8n:5678', 'n8n-db:5432']
    scrape_interval: 15s
    metrics_path: /health
    scheme: http
    scrape_timeout: 5s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

# Remote write configuration (for external monitoring if needed)
# remote_write: []

# Remote read configuration (for external monitoring if needed) 
# remote_read: []

# Security settings
web:
  listen_address: "0.0.0.0:9090"
  max_connections: 512
  read_timeout: 30s
  
# Storage settings
storage:
  retention: "15d"
  retention_size: "1GB"
